### ISSUE TITLE
Issue and warning with Node 10 using ember-cli 3.30

### ISSUE THREAD

**Issue by villander** [embroider-build/ember-auto-import#118]
https://github.com/ember-cli/ember-cli/issues/7995#issuecomment-416971608

**Comment by ef4** [comment]
Thanks for reporting.

**Comment by NullVoxPopuli** [comment]
The minimum supported ember-cli is 3.4, and minimum supported node is 12 (see [engines](https://github.com/embroider-build/ember-auto-import/blob/main/packages/ember-auto-import/package.json#L100)), _and_ since it looks like we found the cause of the problem -- thanks @Turbo87 !! I'm going to close this issue.
