### ISSUE TITLE
Yarn PnP Support?

### ISSUE THREAD

**Issue by rwjblue** [embroider-build/ember-auto-import#143]
I have not done a bunch of exploratory work here, but I _think_ a few changes would be needed here to support `yarn --pnp` apps. I've been exploring what it would take for ember-cli to support this out of the box over in https://github.com/ember-cli/ember-cli/issues/8164.

Perhaps its as simple as configuring https://github.com/arcanis/pnp-webpack-plugin?

**Comment by ef4** [comment]
Yes, this looks pretty straightforward.

**Comment by NullVoxPopuli** [comment]
Given that PnP wasn't broadly adopted by the JavaScript ecosystem (and especially among yarn users), I'm going to close this as "not planned" -- the benefit (to me, at least), doesn't seem good enough. Since this issue was created, we have users of ember on Yarn3/Yarn4 and pnpm, which are much better implementations of dep-management. :partying_face:
