### ISSUE TITLE
Support `include`

### ISSUE THREAD

**Issue by btecu** [embroider-build/ember-auto-import#179]
Can `include` be supported in addition to `exclude`?

**Comment by ef4** [comment]
To get a dependency into your app you already need to _affirmatively ask for it_ in at least two places: you put it into package.json and you write an `import` that targets it.

What would be the benefit of making people write the same thing in a third place?

**Comment by btecu** [comment]
Perhaps I missing something, but currently there's no tree shaking in ember-cli, so using `include` you can manually specify what should be bundled in vendor, otherwise everything is included for the time being. Is this incorrect?

**Comment by ef4** [comment]
I don't really understand your question.  Whether or not the rest of ember-cli supports tree shaking has nothing to do with what we do in ember-auto-import. And ember-auto-import is a pull-based system, there's nothing to shake out because things can only get _in_ by being used.

Can you give me an example of a file that would be added by ember-auto-import when it isn't actually needed?

**Comment by ef4** [comment]
In any case, thanks for asking -- this kind of question helps us figure out what needs to be explained better.

**Comment by btecu** [comment]
@ef4 there actually appears to be a use case for `includes`.
There's an addon (`ember-date-fns`) that's bring parts of a library (`date-fns`) and we'd like to allow the host ember application to import more. Currently it doesn't appear to work, so an `includes` option would be great.

See https://github.com/oskarrough/ember-date-fns/pull/15.

**Comment by ef4** [comment]
> allow the host ember application to import more

The way we allow an application to import more things is by using `import`. That's the entire point of this addon. If the app wants to import some particular function from `date-fns`, it should just do that directly.

I can imagine two possible sources of confusion here.

One is that in order for the app to import directly from `date-fns`, it's not enough for the app to have a dependency on `ember-date-fns`, it needs its own direct dependency on `date-fns`. If you want to support this case and guarantee that the app and `ember-date-fns` will share exactly the same copy of `date-fns`, you should make `date-fns` a `peerDependency` of `ember-date-fns` and add it to the app's dependencies via a blueprint (as opposed to bringing it in as a dependency of `ember-date-fns`).

The second possible confusion is that ember-auto-import doesn't import things out of Ember addons themselves. Ember addons already have strong opinions about how they build themselves, and we don't mess with that. So you can't put some code _inside_ `ember-date-fns` that gets pulled into the app on demand by ember-auto-import.

**Comment by NullVoxPopuli** [comment]
It looks like the resolution here is to use dependency declaration conventions from package.json in combination with using imports to get dependencies (or certain versions of dependencies) included in your app.

This rule is universal, across all of JS: from an app perspective, **if you import it, you must declare it** in package.json

From a library perspective, and as a library author, if you need the app to provide a "source of truth" or "single copy" of a dependency, you want to declare your library's need of that dependency as a peer dependency.

For example, in [`ember-moment`](https://github.com/adopted-ember-addons/ember-moment/blob/master/package.json), `moment` is a peerDependency because we don't want to accidentally introduce `moment` more than once in an app (not just because moment is large, but for other libraries which utilize module state, multiple inclusions can be catastrophic). 


In any case, if there is still an issue here, please open a new issue and we can discuss the specifics there :sparkles: thank you!!!
